sudo rm -r /usr/local/bin/cartographer_autogenerate_ground_truth
sudo rm -r /usr/local/bin/cartographer_compute_relations_metrics
sudo rm -r /usr/local/bin/cartographer_pbstream
sudo rm -r /usr/local/bin/cartographer_print_configuration
sudo rm -r /usr/local/include/cartographer/common/configuration_file_resolver.h
sudo rm -r /usr/local/include/cartographer/common/fixed_ratio_sampler.h
sudo rm -r /usr/local/include/cartographer/common/histogram.h
sudo rm -r /usr/local/include/cartographer/common/lua.h
sudo rm -r /usr/local/include/cartographer/common/lua_parameter_dictionary.h
sudo rm -r /usr/local/include/cartographer/common/math.h
sudo rm -r /usr/local/include/cartographer/common/port.h
sudo rm -r /usr/local/include/cartographer/common/proto/ceres_solver_options.pb.h
sudo rm -r /usr/local/include/cartographer/common/task.h
sudo rm -r /usr/local/include/cartographer/common/thread_pool.h
sudo rm -r /usr/local/include/cartographer/common/time.h
sudo rm -r /usr/local/include/cartographer/ground_truth/autogenerate_ground_truth.h
sudo rm -r /usr/local/include/cartographer/ground_truth/proto/relations.pb.h
sudo rm -r /usr/local/include/cartographer/ground_truth/relations_text_file.h
sudo rm -r /usr/local/include/cartographer/io/color.h
sudo rm -r /usr/local/include/cartographer/io/coloring_points_processor.h
sudo rm -r /usr/local/include/cartographer/io/counting_points_processor.h
sudo rm -r /usr/local/include/cartographer/io/draw_trajectories.h
sudo rm -r /usr/local/include/cartographer/io/fake_file_writer.h
sudo rm -r /usr/local/include/cartographer/io/file_writer.h
sudo rm -r /usr/local/include/cartographer/io/fixed_ratio_sampling_points_processor.h
sudo rm -r /usr/local/include/cartographer/io/frame_id_filtering_points_processor.h
sudo rm -r /usr/local/include/cartographer/io/hybrid_grid_points_processor.h
sudo rm -r /usr/local/include/cartographer/io/image.h
sudo rm -r /usr/local/include/cartographer/io/intensity_to_color_points_processor.h
sudo rm -r /usr/local/include/cartographer/io/min_max_range_filtering_points_processor.h
sudo rm -r /usr/local/include/cartographer/io/null_points_processor.h
sudo rm -r /usr/local/include/cartographer/io/outlier_removing_points_processor.h
sudo rm -r /usr/local/include/cartographer/io/pcd_writing_points_processor.h
sudo rm -r /usr/local/include/cartographer/io/ply_writing_points_processor.h
sudo rm -r /usr/local/include/cartographer/io/points_batch.h
sudo rm -r /usr/local/include/cartographer/io/points_processor.h
sudo rm -r /usr/local/include/cartographer/io/points_processor_pipeline_builder.h
sudo rm -r /usr/local/include/cartographer/io/probability_grid_points_processor.h
sudo rm -r /usr/local/include/cartographer/io/proto_stream.h
sudo rm -r /usr/local/include/cartographer/io/proto_stream_deserializer.h
sudo rm -r /usr/local/include/cartographer/io/proto_stream_interface.h
sudo rm -r /usr/local/include/cartographer/io/serialization_format_migration.h
sudo rm -r /usr/local/include/cartographer/io/submap_painter.h
sudo rm -r /usr/local/include/cartographer/io/vertical_range_filtering_points_processor.h
sudo rm -r /usr/local/include/cartographer/io/xray_points_processor.h
sudo rm -r /usr/local/include/cartographer/io/xyz_writing_points_processor.h
sudo rm -r /usr/local/include/cartographer/mapping/2d/grid_2d.h
sudo rm -r /usr/local/include/cartographer/mapping/2d/map_limits.h
sudo rm -r /usr/local/include/cartographer/mapping/2d/probability_grid.h
sudo rm -r /usr/local/include/cartographer/mapping/2d/probability_grid_range_data_inserter_2d.h
sudo rm -r /usr/local/include/cartographer/mapping/2d/submap_2d.h
sudo rm -r /usr/local/include/cartographer/mapping/2d/xy_index.h
sudo rm -r /usr/local/include/cartographer/mapping/3d/hybrid_grid.h
sudo rm -r /usr/local/include/cartographer/mapping/3d/range_data_inserter_3d.h
sudo rm -r /usr/local/include/cartographer/mapping/3d/submap_3d.h
sudo rm -r /usr/local/include/cartographer/mapping/detect_floors.h
sudo rm -r /usr/local/include/cartographer/mapping/grid_interface.h
sudo rm -r /usr/local/include/cartographer/mapping/id.h
sudo rm -r /usr/local/include/cartographer/mapping/imu_tracker.h
sudo rm -r /usr/local/include/cartographer/mapping/map_builder.h
sudo rm -r /usr/local/include/cartographer/mapping/map_builder_interface.h
sudo rm -r /usr/local/include/cartographer/mapping/pose_extrapolator.h
sudo rm -r /usr/local/include/cartographer/mapping/pose_extrapolator_interface.h
sudo rm -r /usr/local/include/cartographer/mapping/pose_graph.h
sudo rm -r /usr/local/include/cartographer/mapping/pose_graph_interface.h
sudo rm -r /usr/local/include/cartographer/mapping/pose_graph_trimmer.h
sudo rm -r /usr/local/include/cartographer/mapping/probability_values.h
sudo rm -r /usr/local/include/cartographer/mapping/proto/cell_limits_2d.pb.h
sudo rm -r /usr/local/include/cartographer/mapping/proto/connected_components.pb.h
sudo rm -r /usr/local/include/cartographer/mapping/proto/grid_2d.pb.h
sudo rm -r /usr/local/include/cartographer/mapping/proto/grid_2d_options.pb.h
sudo rm -r /usr/local/include/cartographer/mapping/proto/hybrid_grid.pb.h
sudo rm -r /usr/local/include/cartographer/mapping/proto/local_trajectory_builder_options_2d.pb.h
sudo rm -r /usr/local/include/cartographer/mapping/proto/local_trajectory_builder_options_3d.pb.h
sudo rm -r /usr/local/include/cartographer/mapping/proto/map_builder_options.pb.h
sudo rm -r /usr/local/include/cartographer/mapping/proto/map_limits.pb.h
sudo rm -r /usr/local/include/cartographer/mapping/proto/motion_filter_options.pb.h
sudo rm -r /usr/local/include/cartographer/mapping/proto/normal_estimation_options_2d.pb.h
sudo rm -r /usr/local/include/cartographer/mapping/proto/pose_extrapolator_options.pb.h
sudo rm -r /usr/local/include/cartographer/mapping/proto/pose_graph.pb.h
sudo rm -r /usr/local/include/cartographer/mapping/proto/pose_graph/constraint_builder_options.pb.h
sudo rm -r /usr/local/include/cartographer/mapping/proto/pose_graph/optimization_problem_options.pb.h
sudo rm -r /usr/local/include/cartographer/mapping/proto/pose_graph_options.pb.h
sudo rm -r /usr/local/include/cartographer/mapping/proto/probability_grid.pb.h
sudo rm -r /usr/local/include/cartographer/mapping/proto/probability_grid_range_data_inserter_options_2d.pb.h
sudo rm -r /usr/local/include/cartographer/mapping/proto/range_data_inserter_options.pb.h
sudo rm -r /usr/local/include/cartographer/mapping/proto/range_data_inserter_options_3d.pb.h
sudo rm -r /usr/local/include/cartographer/mapping/proto/scan_matching/ceres_scan_matcher_options_2d.pb.h
sudo rm -r /usr/local/include/cartographer/mapping/proto/scan_matching/ceres_scan_matcher_options_3d.pb.h
sudo rm -r /usr/local/include/cartographer/mapping/proto/scan_matching/fast_correlative_scan_matcher_options_2d.pb.h
sudo rm -r /usr/local/include/cartographer/mapping/proto/scan_matching/fast_correlative_scan_matcher_options_3d.pb.h
sudo rm -r /usr/local/include/cartographer/mapping/proto/scan_matching/real_time_correlative_scan_matcher_options.pb.h
sudo rm -r /usr/local/include/cartographer/mapping/proto/serialization.pb.h
sudo rm -r /usr/local/include/cartographer/mapping/proto/submap.pb.h
sudo rm -r /usr/local/include/cartographer/mapping/proto/submap_visualization.pb.h
sudo rm -r /usr/local/include/cartographer/mapping/proto/submaps_options_2d.pb.h
sudo rm -r /usr/local/include/cartographer/mapping/proto/submaps_options_3d.pb.h
sudo rm -r /usr/local/include/cartographer/mapping/proto/trajectory.pb.h
sudo rm -r /usr/local/include/cartographer/mapping/proto/trajectory_builder_options.pb.h
sudo rm -r /usr/local/include/cartographer/mapping/proto/trajectory_node_data.pb.h
sudo rm -r /usr/local/include/cartographer/mapping/proto/tsdf_2d.pb.h
sudo rm -r /usr/local/include/cartographer/mapping/proto/tsdf_range_data_inserter_options_2d.pb.h
sudo rm -r /usr/local/include/cartographer/mapping/range_data_inserter_interface.h
sudo rm -r /usr/local/include/cartographer/mapping/submaps.h
sudo rm -r /usr/local/include/cartographer/mapping/trajectory_builder_interface.h
sudo rm -r /usr/local/include/cartographer/mapping/trajectory_node.h
sudo rm -r /usr/local/include/cartographer/mapping/value_conversion_tables.h
sudo rm -r /usr/local/include/cartographer/metrics/counter.h
sudo rm -r /usr/local/include/cartographer/metrics/family_factory.h
sudo rm -r /usr/local/include/cartographer/metrics/gauge.h
sudo rm -r /usr/local/include/cartographer/metrics/histogram.h
sudo rm -r /usr/local/include/cartographer/metrics/register.h
sudo rm -r /usr/local/include/cartographer/sensor/collator_interface.h
sudo rm -r /usr/local/include/cartographer/sensor/compressed_point_cloud.h
sudo rm -r /usr/local/include/cartographer/sensor/data.h
sudo rm -r /usr/local/include/cartographer/sensor/fixed_frame_pose_data.h
sudo rm -r /usr/local/include/cartographer/sensor/imu_data.h
sudo rm -r /usr/local/include/cartographer/sensor/landmark_data.h
sudo rm -r /usr/local/include/cartographer/sensor/map_by_time.h
sudo rm -r /usr/local/include/cartographer/sensor/odometry_data.h
sudo rm -r /usr/local/include/cartographer/sensor/point_cloud.h
sudo rm -r /usr/local/include/cartographer/sensor/proto/adaptive_voxel_filter_options.pb.h
sudo rm -r /usr/local/include/cartographer/sensor/proto/sensor.pb.h
sudo rm -r /usr/local/include/cartographer/sensor/range_data.h
sudo rm -r /usr/local/include/cartographer/sensor/rangefinder_point.h
sudo rm -r /usr/local/include/cartographer/sensor/timed_point_cloud_data.h
sudo rm -r /usr/local/include/cartographer/transform/proto/timestamped_transform.pb.h
sudo rm -r /usr/local/include/cartographer/transform/proto/transform.pb.h
sudo rm -r /usr/local/include/cartographer/transform/rigid_transform.h
sudo rm -r /usr/local/include/cartographer/transform/rigid_transform_test_helpers.h
sudo rm -r /usr/local/include/cartographer/transform/timestamped_transform.h
sudo rm -r /usr/local/include/cartographer/transform/transform.h
sudo rm -r /usr/local/include/cartographer/transform/transform_interpolation_buffer.h
sudo rm -r /usr/local/lib/libcartographer.a
sudo rm -r /usr/local/share/cartographer/cartographer-config.cmake
sudo rm -r /usr/local/share/cartographer/cmake/CartographerTargets-release.cmake
sudo rm -r /usr/local/share/cartographer/cmake/CartographerTargets.cmake
sudo rm -r /usr/local/share/cartographer/cmake/functions.cmake
sudo rm -r /usr/local/share/cartographer/cmake/modules/FindEigen3.cmake
sudo rm -r /usr/local/share/cartographer/cmake/modules/FindGMock.cmake
sudo rm -r /usr/local/share/cartographer/cmake/modules/FindLuaGoogle.cmake
sudo rm -r /usr/local/share/cartographer/cmake/modules/FindSphinx.cmake
sudo rm -r /usr/local/share/cartographer/configuration_files/map_builder.lua
sudo rm -r /usr/local/share/cartographer/configuration_files/map_builder_server.lua
sudo rm -r /usr/local/share/cartographer/configuration_files/pose_graph.lua
sudo rm -r /usr/local/share/cartographer/configuration_files/trajectory_builder.lua
sudo rm -r /usr/local/share/cartographer/configuration_files/trajectory_builder_2d.lua
sudo rm -r /usr/local/share/cartographer/configuration_files/trajectory_builder_3d.lua
sudo rm -r /usr/local/share/cartographer/package.xml